[package]
name = "check-oracle-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
solana-program = "1.18.2"
cambrian-rust-sdk = { path = "../cambrian-rust-sdk" }