[package]
name = "check-oracle-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-program = "1.18.2"
base58 = "0.2"
serde_repr = "0.1"